###
###     Makefile for FNDemoPhone
###
###             generated for UNIX/LINUX environments
###             by elon
###

BINDIR= bin
#INCDIR= inc
#SRCDIR= src
#OBJDIR= obj
#CC=gcc
CXX=g++
#CFLAG += -I inc
#LINK = g++ -g -Wl --hash-style=sysv

#TARGET = test
#OBJ = Main.o \
#			NetClass.o \
			
			
# -lFnVpu 
#all: $(TARGET)
#$(TARGET): LinkedList.cpp
divuniter : main.cpp 
	$(CXX) main.cpp -o $(BINDIR)/DivUniter
#$(OBJDIR)/%.d: $(SRCDIR)/%.cpp
#	$(CXX) -MM $(CPPFLAGS) $< > $@.temp;
#	sed 's,\($*\)\.o[ :]*,\1.o $@ : ,g' < $@.temp > $@;
#	rm -f $(OBJDIR)/@.temp

#sinclude $(OBJ:.o=.d) 

#%.o: $(SRCDIR)/%.cpp
#	$(CXX)  $(CFLAG) -g -c -o2 $< -o $(OBJDIR)/$@

#%.o: $(SRCDIR)/%.c 
#	$(CC)   $(CFLAG) -g -c -o2 $< -o $(OBJDIR)/$@

#.PHONY: clean
#clean:
#	rm -f $(OBJDIR)/*.o $(OBJDIR)/*.out $(OBJDIR)/*.d
#install-pro:
#	cp $(BINDIR)/$(TARGET) /opt/nfs/rootfs/home/yaoquan/
