#define PACKAGE_NAME "Sort"
#define PACKAGE_TARNAME "sort"
#define PACKAGE_VERSION "1.0"
#define PACKAGE_STRING "Sort 1.0"
#define PACKAGE_BUGREPORT "BUG-REPORT-ADDRESS"
#define PACKAGE "thread"
#define VERSION "1.0"
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
