#define PACKAGE_NAME "reader"
#define PACKAGE_TARNAME "reader"
#define PACKAGE_VERSION "1.0"
#define PACKAGE_STRING "reader 1.0"
#define PACKAGE_BUGREPORT "BUG-REPORT-ADDRESS"
#define PACKAGE "reader"
#define VERSION "1.0"
#define HAVE_LIBPTHREAD 1
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_UNISTD_H 1
#define TIME_WITH_SYS_TIME 1
#define HAVE_STDLIB_H 1
#define HAVE_MALLOC 1
#define HAVE_MEMSET 1
#define HAVE_STPCPY 1
#define HAVE_STRNDUP 1
