package org.apache.musicplf.domain;

public class AlbumWithBLOBs extends Album {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column album.image
     *
     * @ibatorgenerated Fri Jul 16 11:14:00 CST 2010
     */
    private byte[] image;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column album.remark
     *
     * @ibatorgenerated Fri Jul 16 11:14:00 CST 2010
     */
    private String remark;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column album.image
     *
     * @return the value of album.image
     *
     * @ibatorgenerated Fri Jul 16 11:14:00 CST 2010
     */
    public byte[] getImage() {
        return image;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column album.image
     *
     * @param image the value for album.image
     *
     * @ibatorgenerated Fri Jul 16 11:14:00 CST 2010
     */
    public void setImage(byte[] image) {
        this.image = image;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column album.remark
     *
     * @return the value of album.remark
     *
     * @ibatorgenerated Fri Jul 16 11:14:00 CST 2010
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column album.remark
     *
     * @param remark the value for album.remark
     *
     * @ibatorgenerated Fri Jul 16 11:14:00 CST 2010
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}